#include <iostream>
using namespace std;

int main() {
  // s using to give write space before the mini heart! 
  string s= "        ";
  cout <<endl<<endl<<"\n\n\n\n";
  /* to shoe mini heart
     using both of space and * character */
  cout<< s << "    **   **   "<<endl;
  cout<< s << "   *   *   *  "<<endl;
  cout<< s << "    *     *   "<<endl;
  cout<< s << "       *      "<<endl;
  return 0;
  
}
